#!/bin/bash


echo "Run filter script? y/n"
read usr_resp
if [[ $usr_resp = "Y" || $usr_resp == "y" ]]; then
	echo "Enter word to filter by:"
	read word_filtered
	echo "Filtering using $word_filtered..."
	filtered_text=$(cat "New Text Document.txt"| grep $word_filtered)
	printf "$filtered_text\n" > "filtered_text.txt"
	echo "Filtering done!"

	echo "Enter replaced word:"
	read replaced_word
	echo "Enter replacee word:"
	read replacee_word
	echo "OK! Replacing $replaced_word with $replacee_word..."
	replaced_text=$(cat "filtered_text.txt"| sed s/$replaced_word/$replacee_word/g)
	printf "$replaced_text\n" > "replaced_text.txt"
	echo "Replacing done!"
	
else

	echo "Enter replaced word:"
	read replaced_word
	echo "Enter replacee word:"
	read replacee_word
	echo "OK! Replacing $replaced_word with $replacee_word..."
	replaced_text=$(cat "New Text Document.txt"| sed s/$replaced_word/$replacee_word/g)
	printf "$replaced_text\n" > "replaced_text.txt"
	echo "Replacing done!"

fi

#for 1:length
